### PR TITLE
GH Actions: Fix Windows build

### PR DESCRIPTION
**Pull request by bacv**
`continue-on-error` didn't yield the desired behavior of marking the job failed, but performing other runs - removing it. 
The issue described here: [#365](https://github.com/logos-co/nomos-node/pull/365#discussion_r1312728853)

### CODE REVIEW

**Review by youngjoon-lee — APPROVED** [review]
thank you!

**Comment by bacv** [comment]
@danielSanchezQ seems that we have problems building nomos waku node on windows: https://github.com/logos-co/nomos-node/actions/runs/6047698116/job/16411636481?pr=367#step:5:1013

I can look into it, or we could skip waku for windows for now.

**Comment by danielSanchezQ** [comment]
> @danielSanchezQ seems that we have problems building nomos waku node on windows: https://github.com/logos-co/nomos-node/actions/runs/6047698116/job/16411636481?pr=367#step:5:1013
> 
> I can look into it, or we could skip waku for windows for now.

Probably is because we need to use the gnu toolchains in windows for waku. It do not work with msvc.

**Review by youngjoon-lee — APPROVED** [review]
👍

**Comment by youngjoon-lee** [comment]
@bacv Ah, sorry. I missed the https://github.com/logos-co/nomos-node/pull/367/commits/25567017ef10e07db918b4da2bb8f5d2320fd809 which disables integration tests. Do we need to disable integration test to speed up CI jobs?

**Pull request merged**
