### PR TITLE
refactor(tests): Gather utilities

### PR DESCRIPTION
**Pull request by AlejandroCabeza**
## 1. What does this PR implement?
Move some test-related to a crate so it can be reused and set an example of how we could do that.
Closes: https://github.com/logos-co/nomos-node/issues/947

## 2. Does the code have enough context to be clearly understood?
Yes

## 3. Who are the specification authors and who is accountable for this PR?
@AlejandroCabeza 

## 4. Is the specification accurate and complete?
N/A

## 5. Does the implementation introduce changes in the specification?
N/A

## Checklist

> [!WARNING]  
> Do not merge the PR if any of the following is missing:

* [X] 1. Description added.
* [X] 2. Context and links to Specification document(s) added.
* [X] 3. Main contact(s) (developers and specification authors) added
* [X] 4. Implementation and Specification are 100% in sync including changes. This is critical.
* [X] 5. Link PR to a specific milestone.

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
Uhm, this is not bad per se. But maybe we could have feature gated them in the `kzgrs_backend` crate directly.

**Comment by AlejandroCabeza** [comment]
> Uhm, this is not bad per se. But maybe we could have feature gated them in the `kzgrs_backend` crate directly.

I thought about that, but it comes with a con: If you gate utilities under a feature you need to manually enable them when you run the tests. Doing it this way means no configuration needs to be modified (specially for RustRover users, because running tests with features enabled requires a few extra clicks).

**Comment by danielSanchezQ** [comment]
> > Uhm, this is not bad per se. But maybe we could have feature gated them in the `kzgrs_backend` crate directly.
> 
> I thought about that, but it comes with a con: If you gate utilities under a feature you need to manually enable them when you run the tests. Doing it this way means no configuration needs to be modified (specially for RustRover users, because running tests with features enabled requires a few extra clicks).

That claim is not enterily true, you can add the depencency ad a dev-dependency enabling the feature just for dev purposes (testing).

**Comment by AlejandroCabeza** [comment]
> > > Uhm, this is not bad per se. But maybe we could have feature gated them in the `kzgrs_backend` crate directly.
> > 
> > 
> > I thought about that, but it comes with a con: If you gate utilities under a feature you need to manually enable them when you run the tests. Doing it this way means no configuration needs to be modified (specially for RustRover users, because running tests with features enabled requires a few extra clicks).
> 
> That claim is not entirely true, you can add the dependency ad a dev-dependency enabling the feature just for dev purposes (testing).

Now that you mention it you're right. I don't know how I ended up overlooking that. Changing it.

**Review by danielSanchezQ — APPROVED** [review]

**Pull request merged**
