### PR TITLE
fix: Coverage and PR workflows - no space left on device

### PR DESCRIPTION
**Pull request by romanzac**
## What does this PR implement?

- Remove Android, Dotnet and Haskell support from Ubuntu Github runner to free up disk space. About 15 GB freed. 
- Add local `actions/prune-vm`
- Update coverage and PR workflows

### CODE REVIEW

**Comment by romanzac** [comment]
Hi @bacv, we can use `AdityaGarg8/remove-unwanted-software@v4.1` for PR workflow as well. Let me know, I can prepare the fix. It is a bit of a hack, but works instantly.

**Comment by bacv** [comment]
I would prefer not to use this, unless https://github.com/status-im/infra-misc/issues/364 takes more time to be closed.

In that case lets fork the action and pull changes from upstream only after reviewing them. Would DST team be willing to take maintenance of this action?

@apentori do  you think we should wait for self hosted runners or add temporal solution?

**Comment by romanzac** [comment]
> I would prefer not to use this, unless [status-im/infra-misc#364](https://github.com/status-im/infra-misc/issues/364) takes more time to be closed.
> 
> In that case lets fork the action and pull changes from upstream only after reviewing them. Would DST team be willing to take maintenance of this action?
> 
> @apentori do you think we should wait for self hosted runners or add temporal solution?

Another alternative is to add rm command to our wfs? It is all what it does:
https://github.com/AdityaGarg8/remove-unwanted-software/blob/8831c82abf29b34eb2caac48d5f999ecfc0d8eef/action.yml#L95

**Comment by romanzac** [comment]
> > Another alternative is to add rm command to our wfs? It is all what it does:
> 
> This could be added as self contained action in `.github/actions/prune-vm` or similar with `dotnet` and `android` deps removed. We would still rely on undocumented github stuff, but it would be slightly easier to track changes done to it if something stops working.

Fixed both workflows since https://github.com/logos-co/nomos-node/pull/798/commits/4c4498236dc070ea2fa295208591345d5bd50ac8

**Review by bacv — APPROVED** [review]
Thank you for looking into this and solving it!

**Pull request merged**
