### PR TITLE
Refactor libp2p network backend

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Refactored the verbose code block in the async task.

COMING SOON: Further refactoring in the mixnet branch (for resolving `todo!`s).

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
Going into refactors. I think we could take over branches of those methods as well, ideally looking forward for something lie:

```rust
match x:
    foo(*args) => handle_foo(*args),
    bar(*args) => handle_bar(*args),
    ....
```
Where each branch has its own method.

**Review by Zeegomo — APPROVED** [review]

**Review by al8n — APPROVED** [review]

**Comment by youngjoon-lee** [comment]
> Going into refactors. I think we could take over branches of those methods as well, ideally looking forward for something lie:
> 
> ```rust
> match x:
>     foo(*args) => handle_foo(*args),
>     bar(*args) => handle_bar(*args),
>     ....
> ```
> 
> Where each branch has its own method.
Yeah, I agree. I'm going to work on it after cleaning up some stuff in the mixnet branch, since there are more things to be refactored the entire code structure could be changed by it.

**Comment by youngjoon-lee** [comment]
I'll postpone this PR until we have a working version of testnet with mixnet that was already merged into master.

**Comment by youngjoon-lee** [comment]
Closing this PR since we may need more fundamental refactorings

**Pull request closed without merging**
