### PR TITLE
Use rocksdb as the backend

### PR DESCRIPTION
**Pull request by al8n**
Based on #584.

### CODE REVIEW

**Review by youngjoon-lee — APPROVED** [review]

**Review by danielSanchezQ — APPROVED** [review]

**Comment by danielSanchezQ** [comment]
@al8n any hint why this fails on windows?

**Comment by al8n** [comment]
> @al8n any hint why this fails on windows? Also one ubuntu...

Actually, I am not sure why the test cases failed. I cannot reproduce it on my local macos and linux (I do not run it on windows as I do not have a windows machine). In another PR action https://github.com/logos-co/nomos-node/actions/runs/8368580943/job/22912908045, the only change in that PR is the tracing registry feature gate, but it also fails randomly.

**Comment by danielSanchezQ** [comment]
> > @al8n any hint why this fails on windows? Also one ubuntu...
> 
> Actually, I am not sure why the test cases failed. I cannot reproduce it on my local macos and linux (I do not run it on windows as I do not have a windows machine). In another PR action https://github.com/logos-co/nomos-node/actions/runs/8368580943/job/22912908045, the only change in that PR is the tracing registry feature gate, but it also fails randomly.

But those errors are independant:
* https://github.com/logos-co/nomos-node/actions/runs/8368580943/job/22912908045, here may be random because it looks is from mixnet.
* In this PR is related to the storage itself.

**Comment by al8n** [comment]
> > > @al8n any hint why this fails on windows? Also one ubuntu...
> > 
> > 
> > Actually, I am not sure why the test cases failed. I cannot reproduce it on my local macos and linux (I do not run it on windows as I do not have a windows machine). In another PR action https://github.com/logos-co/nomos-node/actions/runs/8368580943/job/22912908045, the only change in that PR is the tracing registry feature gate, but it also fails randomly.
> 
> But those errors are independant:
> 
> * https://github.com/logos-co/nomos-node/actions/runs/8368580943/job/22912908045, here, may be random because it looks is from mixnet.
> * In this PR is related to the storage itself.

For Windows, it is a different error. The failure on Ubuntu is the same. I does not have a windows so that I can test it locally.

**Comment by danielSanchezQ** [comment]
Test it locally, work flawlesly. Thanks!!

**Pull request merged**
