### PR TITLE
Reestablish conn with mixnode if err occurs

### PR DESCRIPTION
**Pull request by youngjoon-lee**
I'm reopening the PR #445, now that CI (integration test) is stable. 

99% is the same as the PR #445, but I added an one-line commit: 3414c584fb380dc8df1c97fbb889d870f9a35747. Please double check this, @al8n.

Since #445 has been already reviewed, I didn't assign many reviewers. But, pls feel free to have a look.

### CODE REVIEW

**Review by al8n — APPROVED** [review]
Thanks! LGTM!

**Comment by youngjoon-lee** [comment]
> Thanks! LGTM!

Another CI failure appears :) I'll take a look

**Comment by youngjoon-lee** [comment]
> > Thanks! LGTM!
> 
> Another CI failure appears :) I'll take a look

It's still hard to debug since you cannot see logs from nodes, but CI seems to be failed because CI was busy at that time (similar as https://github.com/logos-co/nomos-node/pull/494 and https://github.com/logos-co/nomos-node/pull/492). I'll re-run CI multple times, and if CI doesn't fail with the same error, I'll merge this PR.

After all, I'll open another PR which helps us to see logs from nodes when CI integration tests fail.

**Comment by danielSanchezQ** [comment]
> > > Thanks! LGTM!
> > 
> > 
> > Another CI failure appears :) I'll take a look
> 
> It's still hard to debug since we cannot see logs from nodes, but CI seems to be failed because CI was busy at that time (similar as #494 and #492). I think this PR didn't affect to the CI failure because this PR is very simple and doesn't change the normal behavior. I'll re-run CI multple times, and if CI doesn't fail with the same error, I'll merge this PR.
> 
> After all, I'll open another PR which helps us to see logs from nodes when CI integration tests fail.

So, looks like issue is in windows right?

**Why windows why???**

**Comment by youngjoon-lee** [comment]
> So, looks like issue is in windows right?
>
> Why windows why???

It seems it's not only in windows. Codecov in ubuntu also fails with the similar (but maybe different) symptom. I'm trying to debug it again before merging this.

**Comment by youngjoon-lee** [comment]
> > So, looks like issue is in windows right?
> > Why windows why???
> 
> It seems it's not only in windows. Codecov in ubuntu also fails with the similar (but maybe different) symptom. I'm trying to debug it again before merging this.

I've found that CIs on Windows are 2~3x slower than Ubuntu for some reason, even for the master branch: https://github.com/logos-co/nomos-node/actions/runs/6743301131/job/18330953687. So, I think the CI failures of this PR aren't related to the changes of this PR. We'll be able to be more confident about it with PR #508 soon.

**Comment by danielSanchezQ** [comment]
> > > So, looks like issue is in windows right?
> > > Why windows why???
> > 
> > 
> > It seems it's not only in windows. Codecov in ubuntu also fails with the similar (but maybe different) symptom. I'm trying to debug it again before merging this.
> 
> I've found that CIs on Windows are 2~3x slower than Ubuntu for some reason, even for the master branch: https://github.com/logos-co/nomos-node/actions/runs/6743301131/job/18330953687. So, I think the CI failures of this PR aren't related to the changes of this PR. We'll be able to be more confident about it with PR #508 soon (If any unexpected error isn't found in the logs, we could say the failure is due to the slow machine).

Sounds good. I will try locally as I have windows myself and post results here.

**Comment by danielSanchezQ** [comment]
Windows tests succeed locally. So probably something going around the gh runner.

**Pull request merged**
