### PR TITLE
fix: Codecov workflow conflicting output directory 

### PR DESCRIPTION
**Pull request by romanzac**
## What does this PR implement?
- Coverage workflow output directory renamed to /tmp/codecov

* [x] 1. Description added.
* [ ] 2. Context and links to Specification document(s) added.
* [ ] 3. Main contact(s) (developers and specification authors) added
* [x] 4. Implementation and Specification are 100% in sync including changes. This is critical.
* [ ] 5. Link PR to a specific milestone.

### CODE REVIEW

**Comment by romanzac** [comment]
Hi @bacv , it looks the images provided by Github are being changed or our build output size changed. Ubuntu-22.04 is no longer viable for us to use and removing software hack is not working due to sudo restrictions. I suggest to switch back to macos-latest  or ubuntu-latest.

**Comment by bacv** [comment]
Lets add `prune-vm` action to codecov too:
```
      - name: Remove unwanted software
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/prune-vm
```
If this doesn't work, we'll use selfhosted. Thanks for keeping an eye on this 💪

**Comment by romanzac** [comment]
> Lets add `prune-vm` action to codecov too:
> 
> ```
>       - name: Remove unwanted software
>         uses: ./.github/actions/prune-vm
> ```
> 
> If this doesn't work, we'll use selfhosted. Thanks for keeping an eye on this 💪

Files could be removed, but we have also problem with `indexer_integration::test_indexer` 

https://github.com/logos-co/nomos-node/actions/runs/11570328415/job/32205882549

**Comment by romanzac** [comment]
> Lets add `prune-vm` action to codecov too:
> 
> ```
>       - name: Remove unwanted software
>         uses: ./.github/actions/prune-vm
> ```
> 
> If this doesn't work, we'll use selfhosted. Thanks for keeping an eye on this 💪

Self hosted works https://github.com/logos-co/nomos-node/actions/runs/11572465099/job/32212516053

**Comment by bacv** [comment]
Looks good, lets revert the target branch and make this PR ready for merging.

**Review by bacv — APPROVED** [review]

**Pull request merged**
