### PR TITLE
chore: Improve coverage workflow

### PR DESCRIPTION
**Pull request by romanzac**
Few changes to tweak coverage workflow to occupy less disk space and run tests.

### CODE REVIEW

**Comment by romanzac** [comment]
Based on tests in my fork original wf would finish successfully, but no coverage would render on codecov.io
https://github.com/romanzac/nomos-node/actions/runs/10845309954
https://app.codecov.io/gh/romanzac/nomos-node/commit/11f0a3b4b8aa7f651915e371e9b2c3e70f6549a9 

Is the infrequent update on https://app.codecov.io/gh/logos-co/nomos-node/commits due to our license ?

**Comment by romanzac** [comment]
Right now, coverage workflow takes around 26 minutes. If that is too long to have it after each push, I can change it as scheduled, once a day for example? 

https://github.com/romanzac/nomos-node/actions/runs/10896693219

**Comment by bacv** [comment]
> Right now, coverage workflow takes around 26 minutes. If that is too long to have it after each push, I can change it as scheduled, once a day for example?

Your suggestion to have coverage workflow less frequently is great, at least for the short term. I think once a day would be a good option. Regarding the changes in PR, I would keep grcov installed with the `binstall`, that would use even less space.

**Review by bacv — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
