### PR TITLE
DA: KZG+RS core

### PR DESCRIPTION
**Pull request by danielSanchezQ**
This implements the kzg and rs core methods.

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
Adding @zeegomo  and @youngjoon-lee as reviwers. All this PRs are gonna be merged into a branch that is not master and need to be intermediated reviewed otherwise just checking for the da-v1 PR is gonna be way too big of a review.

**Comment by danielSanchezQ** [comment]
CI fails as there are many missing parts jet. But all da core tests related are ok. Cannot fix the others atm, we will be completing them in further PRs.

**Review by bacv — APPROVED** [review]
Double checked against the `nomos-spec`, looks great. In the future it will be a breeze to add more test cases.

**Review by youngjoon-lee — COMMENTED** [review]
Looks good, though I don't fully understand math terms, such as root of unity. I need more time to get used to it.

**Pull request merged**
