### PR TITLE
Sampling Test Fix: Resubmission of #858

### PR DESCRIPTION
**Pull request by TakeASwing-420**
@romanzac @danielSanchezQ 
I think committing to this branch will be good as of now(instead of the master branch). Currently, the specs of this PR is same that of #858.
I also intend to contribute on #819 (could not resist myself😋 after seeing that red labels on #900 and #902) in this same PR.

### CODE REVIEW

**Comment by romanzac** [comment]
Hi @TakeASwing-420, what makes you think "committing to this branch will be good as of now(instead of the master branch)"?  Do you have ideas how to resolve #902 ? Rather comment in #819 please. I can correct my test and learn myself.

**Comment by TakeASwing-420** [comment]
I want to actually change some code(The signal indicator) of my original #858 . But that's really not all, I thought this branch is dedicated for da behavior testing...so commiting to this one would be convenient for you.

**Comment by TakeASwing-420** [comment]
> I want to actually change some code(The signal indicator) of my original #858 . But that's really not all, I thought this branch is dedicated for da behavior testing...so I thought commiting to this one would be convenient for you.

Hey actually I could not reply properly as I was not in home.
Replying to the 2nd concern, I am trying to fix that issue #902 ...I need some more time.
As you have said, from now I will write any findings regarding this in #902 itself.
But as I am committing in my GitHub repo the commit history will appear in this PR...

**Comment by danielSanchezQ** [comment]
I think this is more convoluted that it should be. Thanks for the effort. But, due to time bandwidth I'm gonna close this for now.

**Pull request closed without merging**
