### PR TITLE
Block explorer

### PR DESCRIPTION
**Pull request by danielSanchezQ**
This is a first approach to leverage the local store as an API. Offloading tasks from the node itself to keep as simple and lightweight as possible.

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
@bacv Can you check if the API call is enough? Otherwise what should we add to make it viable for canary?

**Comment by bacv** [comment]
> @bacv Can you check if the API call is enough? Otherwise what should we add to make it viable for canary?

On it, I'll also try this branch with the change for consensus pruning. If it works this PR could have pruning and api url set in chat app

**Comment by bacv** [comment]
Chat app at the moment works by first querying a list of blocks from the latest `tip`, then pulling content for each block (receiving blobs).
In this PR we can consider that "block content pulling" is implemented, but it would be great to add block list endpoint, where client could get a list from the latest `tip` (latest tip could still be received directly from consensus - `carnot/info`)

**Comment by danielSanchezQ** [comment]
> Chat app at the moment works by first querying a list of blocks from the latest `tip`, then pulling content for each block (receiving blobs). In this PR we can consider that "block content pulling" is implemented, but it would be great to add block list endpoint, where client could get a list from the latest `tip` (latest tip could still be received directly from consensus - `carnot/info`)

@al8n did you took a look at this comment? Could you open a PR on top of this one to add whats missing?

**Comment by danielSanchezQ** [comment]
Closing because the explorer will take a different approach.

**Pull request closed without merging**
