### PR TITLE
Configure supermajority threshold via envvars

### PR DESCRIPTION
**Pull request by bacv**

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
What is this for exactly? `FlatOverlay`?

**Comment by bacv** [comment]
> What is this for exactly? `FlatOverlay`?

Nomos node is now configured to use TreeOverlay, IIRC nomos node won't allow other overlays?
https://github.com/logos-co/nomos-node/blob/aa69eeca00f4e110d2ae4440422d8cd787c54d45/nodes/nomos-node/src/lib.rs#L63

**Comment by danielSanchezQ** [comment]
> > What is this for exactly? `FlatOverlay`?
> 
> Nomos node is now configured to use TreeOverlay, IIRC nomos node won't allow other overlays?
> 
> https://github.com/logos-co/nomos-node/blob/aa69eeca00f4e110d2ae4440422d8cd787c54d45/nodes/nomos-node/src/lib.rs#L63

But the threshold comes by default right? Or do we override it for testing?

**Comment by bacv** [comment]
Yes, this is just for testing, the default is 2/3:
https://github.com/logos-co/nomos-node/blob/aa69eeca00f4e110d2ae4440422d8cd787c54d45/consensus-engine/src/overlay/tree_overlay/overlay.rs#L18-L22

**Review by youngjoon-lee — APPROVED** [review]
👍

**Review by danielSanchezQ — APPROVED** [review]

**Pull request merged**
